### PR TITLE
fix: add forcePathStyle and enableAccelerate config properties back to the S3 client

### LINKED ISSUE #1098: forcedPathStyle was needed and removed
### Describe the bug

Hi, in the latest version of the AWS SDK forcePathStyle has been removed (https://github.com/awslabs/aws-sdk-kotlin/commit/f6502eb10273ea70bc33712d0d350c1c472266ff) which is a workaround mentioned https://github.com/awslabs/aws-sdk-kotlin/issues/842#issuecomment-1426140171
This has broken the S3 client as described in that bug

### Expected behavior

The s3 workaround to keep working.

### Current behavior

can't use S3 client for CI use case.

### Steps to Reproduce

see original bug for details

### Possible Solution

put back forcedPathStyle

### Context

_No response_

### AWS Kotlin SDK version used

0.33.0-beta 

### Platform (JVM/JS/Native)

JVM

### Operating System and version

Linux

### PR DESCRIPTION
**Pull request by aajtodd**
## Issue \#
fixes #1098 

## Description of changes
https://github.com/awslabs/aws-sdk-kotlin/commit/f6502eb10273ea70bc33712d0d350c1c472266ff erroneously removed the explicit configuration settings `forcePathStyle` and `enableAccelerate` from S3 client config. The intended change was to remove parsing these from CLI specific shared config.

This PR also fixes finalize config to respect the environment/system property settings for `useArnRegion` and `disableMrap` (matching [Java v2](https://github.com/aws/aws-sdk-java-v2/blob/65266c2afdd188930310720e2d3754c614d0d434/services/s3/src/main/java/software/amazon/awssdk/services/s3/S3SystemSetting.java#L27) for the system properties).

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: codegen/smithy-aws-kotlin-codegen/src/main/kotlin/aws/sdk/kotlin/codegen/customization/s3/ClientConfigIntegration.kt [hunk 1]
```diff
@@ -37,10 +54,9 @@ class ClientConfigIntegration : KotlinIntegration {
             """.trimIndent()
         }
 
-        // FIXME: default signer doesn't yet implement sigv4a, default to mrap OFF until it does
```
Comment (lauzadis) [inline codegen/smithy-aws-kotlin-codegen/src/main/kotlin/aws/sdk/kotlin/codegen/customization/s3/ClientConfigIntegration.kt:40]: Isn't this still true?

File: services/s3/common/test/aws/sdk/kotlin/services/s3/internal/FinalizeConfigTest.kt [hunk 2]
```diff
@@ -0,0 +1,100 @@
...
+        )
+        val sharedConfig = asyncLazy { loadAwsSharedConfig(platform) }
+
+        finalizeS3Config(builder, sharedConfig, platform)
+        assertEquals(true, builder.config.useArnRegion)
+        assertEquals(false, builder.config.disableMrap)
+    }
+
+    @Test
+    fun testConfigPropertiesPresent() {
```
Comment (lauzadis) [inline services/s3/common/test/aws/sdk/kotlin/services/s3/internal/FinalizeConfigTest.kt:91]: What is this testing?

**Review by lauzadis — APPROVED** [review]

File: codegen/smithy-aws-kotlin-codegen/src/main/kotlin/aws/sdk/kotlin/codegen/customization/s3/ClientConfigIntegration.kt (hunk 1 above)
Comment (aajtodd) [reply codegen/smithy-aws-kotlin-codegen/src/main/kotlin/aws/sdk/kotlin/codegen/customization/s3/ClientConfigIntegration.kt:40]: We select auth scheme based on the model not on endpoint rules (yet) and we don't support sigv4a yet no matter what. Whether it's enabled or not isn't going to matter I don't think so I just changed it to the "correct" default.

File: services/s3/common/test/aws/sdk/kotlin/services/s3/internal/FinalizeConfigTest.kt (hunk 2 above)
Comment (aajtodd) [reply services/s3/common/test/aws/sdk/kotlin/services/s3/internal/FinalizeConfigTest.kt:91]: That these properties don't accidentally disappear again from codegen.

Comment (ianbotsf) [reply services/s3/common/test/aws/sdk/kotlin/services/s3/internal/FinalizeConfigTest.kt:91]: That's not immediately clear from the code. Can we leave a comment indicating why we have a test with no assertions?

**Review by ianbotsf — CHANGES_REQUESTED** [review]

File: codegen/smithy-aws-kotlin-codegen/src/main/kotlin/aws/sdk/kotlin/codegen/customization/s3/ClientConfigIntegration.kt (hunk 1 above)
Comment (aajtodd) [reply codegen/smithy-aws-kotlin-codegen/src/main/kotlin/aws/sdk/kotlin/codegen/customization/s3/ClientConfigIntegration.kt:40]: not a hill worth dying on, reverting.

**Review by ianbotsf — APPROVED** [review]
