### PR TITLE
fix: correctly terminate pagination for CloudWatch Logs GetLogEvents

### LINKED ISSUE #1326: CloudWatch Logs's GetLogEvents paginator never terminates
### Describe the bug

The CloudWatch Logs client supports a paginator over `GetLogEvents` but using this paginator yields a never-ending `Flow`. The [service API documentation](https://docs.aws.amazon.com/AmazonCloudWatchLogs/latest/APIReference/API_GetLogEvents.html#API_GetLogEvents_ResponseElements) describes how the pagination token returned will be the same as the input token when there are no more records to retrieve. Our pagination logic won't handle this case and will basically continue issuing subsequent API calls which yield empty responses for logs which are no longer _actively_ appending.

### Expected behavior

Other SDKs (e.g., Java v2, JS v3) have added customizations which handle `GetLogEvents`'s non-standard pagination. We should investigate doing the same.

### Current behavior

See above.

### Steps to Reproduce

```kotlin
cloudWatchLogsClient
    .getLogEventsPaginated {
        logGroupName = "..."
        logStreamName = "..."
    }
    .collect { println("Page of log events: ${it.events?.size} records, nextToken = ${it.nextForwardToken}") }
```

### Possible Solution

_No response_

### Context

_No response_

### AWS SDK for Kotlin version

1.2.28

### Platform (JVM/JS/Native)

JVM

### Operating system and version

any

### PR DESCRIPTION
**Pull request by ianbotsf**
## Issue \#

Closes #1326 

## Description of changes

This change adds support for CloudWatch Logs' `GetLogEvents` operation's non-standard pagination termination behavior, namely that the pagination is considered complete when the output token matches the input token.

**Companion PR**: https://github.com/smithy-lang/smithy-kotlin/pull/1140

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: codegen/aws-sdk-codegen/src/main/kotlin/aws/sdk/kotlin/codegen/customization/PaginationEndBehaviorIntegration.kt [hunk 1]
```diff
@@ -0,0 +1,55 @@
...
+import software.amazon.smithy.model.shapes.OperationShape
+import software.amazon.smithy.model.shapes.StructureShape
+import software.amazon.smithy.model.transform.ModelTransformer
+
+private val TRUNCATION_MEMBER_IDS = mapOf(
+    "com.amazonaws.s3#ListParts" to "IsTruncated",
+)
+
+private val IDENTICAL_TOKEN_OPERATION_IDS = setOf(
+    "com.amazonaws.cloudwatchlogs#GetLogEvents",
```
Comment (lauzadis) [inline codegen/aws-sdk-codegen/src/main/kotlin/aws/sdk/kotlin/codegen/customization/PaginationEndBehaviorIntegration.kt:22]: nit: if one exists, it would be good to link to GitHub issue which caused these members to be added

File: services/cloudwatchlogs/e2eTest/src/GetLogEventsPaginatorTest.kt [hunk 2]
```diff
@@ -0,0 +1,186 @@
...
+import kotlin.time.Duration.Companion.seconds
+
+private const val MESSAGES_PER_BATCH = 100
+private const val BATCHES = 10
+private const val TOTAL_MESSAGES = MESSAGES_PER_BATCH * BATCHES
+private val TIMESTAMP_DELTA_PER_MESSAGE = (-1).milliseconds
+private val POLLING_DELAY = 5.seconds
+
+// Uncertain what a reliable value for this is...technically, _any_ amount of empty pages is possible given how
+// token-based pagination works. 🤷
```
Comment (lauzadis) [inline services/cloudwatchlogs/e2eTest/src/GetLogEventsPaginatorTest.kt:28]: I think 5 works!

File: services/cloudwatchlogs/e2eTest/src/GetLogEventsPaginatorTest.kt [hunk 3]
```diff
@@ -0,0 +1,186 @@
...
+            logGroupName = group
+            logStreamName = stream
+        }
+    } catch (e: Throwable) {
+        deleteLogGroup { logGroupName = group }
+        throw e
+    }
+    println("Created log stream $stream")
+
+    return group to stream
```
Comment (lauzadis) [inline services/cloudwatchlogs/e2eTest/src/GetLogEventsPaginatorTest.kt:147]: Do we need to wait any time for these operations' resources to be created?

File: services/cloudwatchlogs/e2eTest/src/GetLogEventsPaginatorTest.kt
Comment (lauzadis) [inline services/cloudwatchlogs/e2eTest/src/GetLogEventsPaginatorTest.kt:1]: Will you need to add new permissions for this service / operations to our internal E2E test account?

**Review by lauzadis — APPROVED** [review]

File: services/cloudwatchlogs/e2eTest/src/GetLogEventsPaginatorTest.kt (hunk 3 above)
Comment (ianbotsf) [reply services/cloudwatchlogs/e2eTest/src/GetLogEventsPaginatorTest.kt:147]: Seemingly not. In all my test runs, it seemed that the group and stream were created by the time the response was received. Of course, CWL's docs don't explicitly _say_ that `PutLogEvents` is eventually consistent but it is anyway so I have no clear guarantee this works, just no evidence of failure yet.

File: services/cloudwatchlogs/e2eTest/src/GetLogEventsPaginatorTest.kt
Comment (ianbotsf) [reply services/cloudwatchlogs/e2eTest/src/GetLogEventsPaginatorTest.kt:1]: Yes, I will. Thank you for the reminder!

File: codegen/aws-sdk-codegen/src/main/kotlin/aws/sdk/kotlin/codegen/customization/PaginationEndBehaviorIntegration.kt [hunk 4]
```diff
@@ -0,0 +1,55 @@
...
+)
+
+/**
+ * Applies [PaginationEndBehaviorTrait] to a manually-curated list of operations/members to handle for non-standard
```
Comment (0marperez) [inline codegen/aws-sdk-codegen/src/main/kotlin/aws/sdk/kotlin/codegen/customization/PaginationEndBehaviorIntegration.kt:26]: nit: looks like there's a stray "for" in here, removing it would make this clearer: `to handle for non-standard pagination termination behavior.` -> `to handle non-standard pagination termination behavior.`

File: codegen/aws-sdk-codegen/src/main/kotlin/aws/sdk/kotlin/codegen/customization/PaginationEndBehaviorIntegration.kt [hunk 5]
```diff
@@ -0,0 +1,55 @@
...
+    override fun preprocessModel(model: Model, settings: KotlinSettings): Model = ModelTransformer
+        .create()
+        .mapShapes(model) { shape ->
+            val shapeId = shape.id.toString()
+            when {
+                shape !is OperationShape -> shape // Pagination behavior trait only applied to operations
+
+                shapeId in TRUNCATION_MEMBER_IDS -> {
+                    val output = model.expectShape(shape.outputShape)
+                    require(output is StructureShape) { "Operation output must be a structure shape" }
```
Comment (0marperez) [inline codegen/aws-sdk-codegen/src/main/kotlin/aws/sdk/kotlin/codegen/customization/PaginationEndBehaviorIntegration.kt:39]: > `require(output is StructureShape) { "Operation output must be a structure shape" }`

question: is this something that we need to check? I think the smithy IDL checks this

**Review by 0marperez — APPROVED** [review]

File: codegen/aws-sdk-codegen/src/main/kotlin/aws/sdk/kotlin/codegen/customization/PaginationEndBehaviorIntegration.kt (hunk 5 above)
Comment (lauzadis) [reply codegen/aws-sdk-codegen/src/main/kotlin/aws/sdk/kotlin/codegen/customization/PaginationEndBehaviorIntegration.kt:39]: I thought the same thing, Smithy does validate this, but I believe it's used to coerce the Kotlin type from a general `Shape` into a `StructureShape`
