### PR TITLE
fix: merge per-op custom metadata to avoid clobbering per-client metadata

### LINKED ISSUE #694: Custom user agent metadata does not appear in User-Agent header
### Describe the bug

When setting custom user age metadata via an `aws.customMetadata.*` system property, the expected values do not show up in requests's `User-Agent` header. Different metadata set via the `aws.frameworkMetadata` property _do_ properly show up so this seems to be unique to custom metadata.

### Expected behavior

Custom metadata set via `aws.customMetadata.*` **are** included in the `User-Agent` header.

### Current behavior

Custom metadata set via `aws.customMetadata.*` **are not** included in the `User-Agent` header.

### Steps to Reproduce

Configure DEBUG-level logging and run the following code:

```kotlin
System.setProperty("aws.customMetadata.foo", "bar")
val s3 = S3Client.fromEnvironment { sdkLogMode = SdkLogMode.LogRequest }
s3.listObjectsV2 { bucket = "<some-bucket>" }
```

View the DEBUG output and inspect the request headers. The `User-Agent` string contains other metadata but not the custom metadata `foo=bar`.

### Possible Solution

_No response_

### Context

_No response_

### AWS Kotlin SDK version used

0.17.6-SNAPSHOT

### Platform (JVM/JS/Native)

OpenJDK Runtime Environment Corretto-17.0.4.8.1 (build 17.0.4+8-LTS)

### Operating System and version

Amazon Linux 2

### PR DESCRIPTION
**Pull request by ianbotsf**
## Issue \#

Closes #694 

## Description of changes

Our existing `UserAgent` middleware clobbers any per-client custom metadata that may have been detected from JVM system properties or environment variables. This change merges the two to avoid loss.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: aws-runtime/aws-http/common/test/aws/sdk/kotlin/runtime/http/middleware/UserAgentTest.kt [hunk 1]
```diff
@@ -108,4 +90,46 @@ class UserAgentTest {
...
+        val uaString = request.headers[USER_AGENT]!!
+
+        uaString.shouldContain("md/foo/bar")
+        uaString.shouldContain("md/baz/quux")
+        uaString.shouldContain("md/blerg/blarg")
+        uaString.shouldNotContain("md/baz/qux") // This was overwritten by "baz/quux"
+    }
+
+    @Test
+    fun itDoesNotClobberExistingCustomMetadata() = runTest {
```
Comment (aajtodd) [inline aws-runtime/aws-http/common/test/aws/sdk/kotlin/runtime/http/middleware/UserAgentTest.kt:119]: nit/suggestion: Good idea to add a comment to the issue this test covers for posterity

e.g.

```kotlin
@Test
fun itDoesNotClobberExistingCustomMetadata() = runTest {
    // see: https://github.com/awslabs/aws-sdk-kotlin/issues/694
}

**Review by aajtodd — APPROVED** [review]

**Review by lucix-aws — APPROVED** [review]
