### PR TITLE
fix: ignore __type when deserializing union for AWS Json protocols

### LINKED ISSUE #1044: Ignore `__type` field when deserializing unions in JSON protocols
An [upcoming release of the Smithy documentation](https://github.com/smithy-lang/smithy/pull/1945) specifies that any field named `__type` should be ignored when deserializing union variants.

### PR DESCRIPTION
**Pull request by 0marperez**
## Issue \#

closes #1044 

## Description of changes

-Added `IgnoreKey` with key `__type` to descriptors when deserializing a union shape for AWS Json protocols 
(AWS Json 1.0, AWS Json 1.1, RestJson 1.0)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: codegen/smithy-aws-kotlin-codegen/src/main/kotlin/aws/sdk/kotlin/codegen/protocols/json/AwsJsonProtocolParserGenerator.kt [hunk 1]
```diff
@@ -0,0 +1,27 @@
...
+
+import software.amazon.smithy.kotlin.codegen.core.KotlinWriter
+import software.amazon.smithy.kotlin.codegen.rendering.protocol.ProtocolGenerator
+import software.amazon.smithy.kotlin.codegen.rendering.protocol.toRenderingContext
+import software.amazon.smithy.kotlin.codegen.rendering.serde.JsonParserGenerator
+import software.amazon.smithy.kotlin.codegen.rendering.serde.JsonSerdeDescriptorGenerator
+import software.amazon.smithy.model.shapes.MemberShape
+import software.amazon.smithy.model.shapes.Shape
+
+class AwsJsonProtocolParserGenerator(
```
Comment (aajtodd) [inline codegen/smithy-aws-kotlin-codegen/src/main/kotlin/aws/sdk/kotlin/codegen/protocols/json/AwsJsonProtocolParserGenerator.kt:16]: **fix** Missing documentation.


Should we rename this (and `AwsJsonProtocolSerdeDescriptorGenerator`) since these aren't specific to the "aws json" protocols? It's a bit confusing but I also don't know that I have a better suggestion at the moment. At the very least we should document that this isn't specific to `awsJson` protocols.

File: codegen/smithy-aws-kotlin-codegen/src/main/kotlin/aws/sdk/kotlin/codegen/protocols/json/AwsJsonProtocolSerdeDescriptorGenerator.kt [hunk 2]
```diff
@@ -0,0 +1,36 @@
...
+import software.amazon.smithy.kotlin.codegen.core.RenderingContext
+import software.amazon.smithy.kotlin.codegen.core.RuntimeTypes
+import software.amazon.smithy.kotlin.codegen.rendering.serde.JsonSerdeDescriptorGenerator
+import software.amazon.smithy.kotlin.codegen.rendering.serde.SdkFieldDescriptorTrait
+import software.amazon.smithy.kotlin.codegen.rendering.serde.add
+import software.amazon.smithy.kotlin.codegen.utils.dq
+import software.amazon.smithy.model.shapes.MemberShape
+import software.amazon.smithy.model.shapes.Shape
+
+class AwsJsonProtocolSerdeDescriptorGenerator(
```
Comment (aajtodd) [inline codegen/smithy-aws-kotlin-codegen/src/main/kotlin/aws/sdk/kotlin/codegen/protocols/json/AwsJsonProtocolSerdeDescriptorGenerator.kt:17]: Missing docs

File: .changes/ac672b00-f8bb-4235-8db4-aad0ae2f157d.json [hunk 3]
```diff
@@ -0,0 +1,8 @@
+{
+    "id": "ac672b00-f8bb-4235-8db4-aad0ae2f157d",
+    "type": "bugfix",
+    "description": "ignore __type when deserializing union for AWS Json protocols",
```
Comment (lauzadis) [inline .changes/ac672b00-f8bb-4235-8db4-aad0ae2f157d.json:4]: It also applies for RestJSON, so I wouldn't say just "AWS Json protocols"

Comment (lauzadis) [reply .changes/ac672b00-f8bb-4235-8db4-aad0ae2f157d.json:4]: nit: consider wrapping __type in backticks: `__type`

**Review by lauzadis — APPROVED** [review]

File: codegen/smithy-aws-kotlin-codegen/src/main/kotlin/aws/sdk/kotlin/codegen/protocols/json/AwsJsonProtocolSerdeDescriptorGenerator.kt [hunk 4]
```diff
@@ -0,0 +1,46 @@
...
+ */
+class AwsJsonProtocolSerdeDescriptorGenerator(
+    ctx: RenderingContext<Shape>,
+    memberShapes: List<MemberShape>? = null,
+    supportsJsonNameTrait: Boolean = true,
+) : JsonSerdeDescriptorGenerator(ctx, memberShapes, supportsJsonNameTrait) {
+
+    /**
+     * Adds a trait to ignore `__type` in union shapes for `AWS Json 1.0`, `AWS Json 1.1`, `RestJson 1.0` protocols
+     * Sometimes the unnecessary trait `__type` is added and needs to be ignored
```
Comment (ianbotsf) [inline codegen/smithy-aws-kotlin-codegen/src/main/kotlin/aws/sdk/kotlin/codegen/protocols/json/AwsJsonProtocolSerdeDescriptorGenerator.kt:30]: **Nit**: "Sometimes the unnecessary _field_ \`__type\` is added and needs to be ignored"

**Review by ianbotsf — APPROVED** [review]

**Review by aajtodd — APPROVED** [review]
