### PR TITLE
fix(rt): import signing test suite

### LINKED ISSUE #448: S3 requests with prefix/delimiter containing URLEncodable characters will fail signature validation
## Describe the bug

S3 requests with prefix/delimiter containing URLEncodable characters will fail signature validation

## Expected Behavior

Expect to be able to use `/` as a delimiter in file object keys, and filter based on a prefix containing the delimiter character.

## Current Behavior

Cases for signature creation:

| delimiter | prefix  | outcome |
|-----------|---------|---------|
| null      | null    | OK      |
| /         | null    | FAIL    |
| /         | folder  | FAIL    |
| /         | folder/ | FAIL    |
| -         | folder  | OK      |
| -         | folder- | OK      |

Seems like characters in either delimiter or prefix that are URLEncodable will fail generating correct signatures.
Java sdk2 seems to run just fine with `/`

```txt
112:23:46.281 TRACE a.s.k.r.h.operation.SerializeHandler sdkRequestId: d8e6e856-acc8-4492-91d7-badc7bc8b9ba; service: S3; operation: ListObjects; - request serialized in 9.423961ms
12:23:46.289 DEBUG ResolveAwsEndpoint                   sdkRequestId: d8e6e856-acc8-4492-91d7-badc7bc8b9ba; service: S3; operation: ListObjects; - resolved endpoint: AwsEndpoint(endpoint=Endpoint(uri=https://s3.eu-central-1.amazonaws.com, isHostnameImmutable=false), credentialScope=CredentialScope(region=eu-central-1, service=null))
12:23:46.353 DEBUG httpTraceMiddleware                  sdkRequestId: d8e6e856-acc8-4492-91d7-badc7bc8b9ba; service: S3; operation: ListObjects; - HttpRequest:
GET /BUCKETNAME?delimiter=%252F&max-keys=1
Host: s3.eu-central-1.amazonaws.com
User-Agent: aws-sdk-kotlin/0.9.3-alpha api/s3/0.9.3-alpha os/macos/11.6 lang/kotlin/1.5.31 md/javaVersion/11.0.10 md/jvmName/OpenJDK_64-Bit_Server_VM md/jvmVersion/11.0.10+9-LTS-sapmachine
x-amz-user-agent: aws-sdk-kotlin/0.9.3-alpha
X-Amz-Date: 20211126T102346Z
x-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
Authorization: [REDACTED], SignedHeaders=host;x-amz-content-sha256;x-amz-date;x-amz-user-agent, Signature=aedd959fec02fffe947a7bb37d45d00b744da0777bc909af3b9eef64c751148b

Exception in thread "main" aws.sdk.kotlin.services.s3.model.S3Exception: The request signature we calculated does not match the signature you provided. Check your key and signing method.
at aws.sdk.kotlin.services.s3.transform.ListObjectsOperationDeserializerKt.throwListObjectsError(ListObjectsOperationDeserializer.kt:136)
at aws.sdk.kotlin.services.s3.transform.ListObjectsOperationDeserializerKt.access$throwListObjectsError(ListObjectsOperationDeserializer.kt:1)
at aws.sdk.kotlin.services.s3.transform.ListObjectsOperationDeserializer.deserialize(ListObjectsOperationDeserializer.kt:42)
at aws.smithy.kotlin.runtime.http.operation.SdkOperationExecutionKt$decorate$3.invoke(SdkOperationExecution.kt:97)
at aws.smithy.kotlin.runtime.http.operation.SdkOperationExecutionKt$decorate$3.invoke(SdkOperationExecution.kt:97)
at aws.smithy.kotlin.runtime.http.operation.DeserializeHandler.call(SdkOperationExecution.kt:153)
at aws.smithy.kotlin.runtime.http.operation.DeserializeHandler$call$1.invokeSuspend(SdkOperationExecution.kt)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
at kotlinx.coroutines.UndispatchedCoroutine.afterResume(CoroutineContext.kt:142)
at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:274)
at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
at MainKt.main(Main.kt:103)
```

## Steps to Reproduce

```kotlin
val rootLogger: Logger = LoggerFactory.getLogger(org.slf4j.Logger.ROOT_LOGGER_NAME) as Logger
rootLogger.level = Level.ALL

val s3Client = S3Client {
    region = "eu-central-1"
    sdkLogMode = SdkLogMode.LogRequestWithBody
}

runBlocking {
    try {
        val listing = s3Client.listObjects {
            this.bucket = "BUCKETNAME"
            maxKeys = 1
            delimiter = "/"
            prefix = null
        }

        val requestContents: List<Object> = listing.contents ?: emptyList()
        requestContents.forEach {
            println("* ${it.key}")
        }
    } catch (ex: AwsServiceException) {
        val httpResp = ex.sdkErrorMetadata.protocolResponse as? HttpResponse
        // Always null
        if (httpResp != null) {
            println(httpResp.headers)
            println(httpResp.body.readAll()?.decodeToString())
        }
        throw ex
    }
}

```
## Possible Solution

Use encoded values when generating the signature.

## Context

Was trying to read s3 objects within a folder hierarchy.

## Your Environment

* AWS Kotlin SDK version used: aws.sdk.kotlin:s3:0.9.3-alpha
* Platform (JVM/JS/Native): JVM
* Operating System and version: MacOS 11.6

### PR DESCRIPTION
**Pull request by aajtodd**
## Issue \#

fixes #448

## Description of changes

* Imported the `aws-c-auth` signing test suite. This at least gives us some confidence that what comes out of the signing process is a valid signed request. Any signing issues after this point *should* theoretically be limited to issues with a particular HTTP engine implementation and their ability to serialize the request on the wire in the expected format.
* Added an e2eTest for the specific issue with S3
* Modified the conversion of `HttpRequestBuilder -> CrtRequest -> HttpRequestBuilder` to only append new/missing keys for headers and query params rather than overwrite. Previously (as described in the ticket) we would just overwrite all the headers and query params from the signed request. CRT request uses the encoded representation of a request which causes (e.g.) any url encoded parameters to get encoded twice when finally going out on the wire.

There are a lot of new files here, most of the relevant changes are in these files:
* aws-runtime/aws-signing/jvm/test/aws/sdk/kotlin/runtime/auth/signing/Sigv4TestSuite.kt
* services/s3/e2eTest/S3IntegrationTest.kt
* aws-runtime/crt-util/common/src/aws/sdk/kotlin/runtime/crt/Http.kt
* aws-runtime/crt-util/common/test/aws/sdk/kotlin/runtime/crt/HttpTest.kt

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: aws-runtime/aws-signing/jvm/test/aws/sdk/kotlin/runtime/auth/signing/Sigv4TestSuite.kt [hunk 1]
```diff
@@ -0,0 +1,405 @@
...
+                config.signatureType = AwsSignatureType.HTTP_REQUEST_VIA_QUERY_PARAMS
+                Sigv4TestSuiteTest(dir, req, sreq, config.build())
+            } catch (ex: Exception) {
+                println("failed to get request from $dir: ${ex.message}")
+                throw ex
+            }
+        }
+
+        testSigv4Middleware(tests)
+    }
```
Comment (ianbotsf) [inline aws-runtime/aws-signing/jvm/test/aws/sdk/kotlin/runtime/auth/signing/Sigv4TestSuite.kt:150]: **Nit**: Duplicated code

**Review by ianbotsf — APPROVED** [review]
Very nice!

File: aws-runtime/aws-signing/jvm/test/aws/sdk/kotlin/runtime/auth/signing/Sigv4TestSuite.kt [hunk 2]
```diff
@@ -0,0 +1,400 @@
...
+        // fixme - revisit why this fails
+        "get-utf8"
+    )
+
+    // get all directories with a request.txt file in it
+    private val testDirs = testSuiteDir
+        .walkTopDown()
+        .filter { !it.isDirectory && it.name == "request.txt" }
+        .filterNot { it.parentFile.name in disabledTests }
+        // .filter{ it.parentFile.name == "get-vanilla-query-order-key-case" }
```
Comment (kggilmer) [inline aws-runtime/aws-signing/jvm/test/aws/sdk/kotlin/runtime/auth/signing/Sigv4TestSuite.kt:94]: nit

seems like dead code

File: aws-runtime/aws-signing/jvm/test/aws/sdk/kotlin/runtime/auth/signing/Sigv4TestSuite.kt [hunk 3]
```diff
@@ -0,0 +1,400 @@
...
+
+        // no signed request to test against
+        "get-vanilla-query-order-key",
+        "get-vanilla-query-order-value",
+
+        // FIXME - crt-java has utf8 bug when converting request,
+        // re-enable after https://github.com/awslabs/aws-crt-java/pull/419 is merged
+        "get-vanilla-utf8-query",
+
+        // fixme - revisit why this fails
```
Comment (kggilmer) [inline aws-runtime/aws-signing/jvm/test/aws/sdk/kotlin/runtime/auth/signing/Sigv4TestSuite.kt:85]: question

does this need more context if someone else digs into it?

File: aws-runtime/aws-signing/jvm/test/aws/sdk/kotlin/runtime/auth/signing/Sigv4TestSuite.kt [hunk 4]
```diff
@@ -0,0 +1,400 @@
...
+        }
+        return tests
+    }
+
+    /**
+     * Run the test suite against the AwsSigv4Middleware implementation
+     */
+    private fun testSigv4Middleware(tests: Sequence<Sigv4TestSuiteTest>): Unit = runBlocking {
+        tests.forEach { test ->
+            // println("running sigv4 middleware test for: ${test.path}")
```
Comment (kggilmer) [inline aws-runtime/aws-signing/jvm/test/aws/sdk/kotlin/runtime/auth/signing/Sigv4TestSuite.kt:152]: nit 

dead code

**Review by kggilmer — APPROVED** [review]

File: aws-runtime/aws-signing/jvm/test/aws/sdk/kotlin/runtime/auth/signing/Sigv4TestSuite.kt (hunk 3 above)
Comment (aajtodd) [reply aws-runtime/aws-signing/jvm/test/aws/sdk/kotlin/runtime/auth/signing/Sigv4TestSuite.kt:85]: no I don't think so. I *think* it will be fixed after the other utf8 issue is fixed but if not it's just a matter of diving into the results.
