### PR TITLE
fix(codegen): disable signing for sts operations AssumeRoleWithSaml and AssumeRoleWithWebIdentity

### LINKED ISSUE #280: AssumeRoleWithWebIdentity should specify no auth in model
## Describe the bug

See quip (df7bAHHjCZBf/AssumeRoleWithWebIdentity-investigation) but in essence AssumeRoleWithWebIdentity is incorrectly modeled by specifying that auth is optional.  In reality this operation requires/uses no authentication so the model should be updated to specify this.

## Expected Behavior
no auth is used when calling AssumeRoleWithWebIdentity

## Current Behavior
auth is used when calling AssumeRoleWithWebIdentity

### PR DESCRIPTION
**Pull request by aajtodd**
## Issue \#

fixes #280 

## Description of changes

* Preprocess the STS model to add empty auth trait (implying that a signed request is optional). 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by kggilmer — APPROVED** [review]
nice tests

File: codegen/smithy-aws-kotlin-codegen/src/main/kotlin/aws/sdk/kotlin/codegen/customization/sts/StsDisableAuthForOperations.kt [hunk 1]
```diff
@@ -0,0 +1,43 @@
...
+    )
+
+    override fun enabledForService(model: Model, settings: KotlinSettings): Boolean =
+        model.expectShape<ServiceShape>(settings.service).sdkId == "STS"
+
+    override fun preprocessModel(model: Model, settings: KotlinSettings): Model =
+        ModelTransformer.create()
+            .mapShapes(model) {
+                if (optionalAuthOperations.contains(it.id) && it is OperationShape) {
+                    it.toBuilder().addTrait(AuthTrait(emptySet())).build()
```
Comment (kggilmer) [inline codegen/smithy-aws-kotlin-codegen/src/main/kotlin/aws/sdk/kotlin/codegen/customization/sts/StsDisableAuthForOperations.kt:38]: suggestion

maybe easier to read to extract the `AuthTrait` instance out into a private property.

**Review by kggilmer — APPROVED** [review]

File: .github/scripts/mk-generated.sh [hunk 2]
```diff
@@ -28,6 +27,15 @@ set -e
   gen_branch="__generated-$current_branch"
   repo_root=$(git rev-parse --show-toplevel)
   cd "$repo_root" && ./gradlew :codegen:sdk:bootstrap
+  # repo may be dirty due to gradle.properties being manipulated to have upstream deps match (e.g. by set_upstream_versions.py)
+  # test that we are running in a GitHub workflow before blowing away any unsaved changes
+  if [[ -z "${GITHUB_WORKFLOW}" ]]; then
+    git diff --quiet || (echo 'working tree not clean, aborting' && exit 1)
+  else
+    echo "working tree dirty, violently resetting HEAD"
```
Comment (ianbotsf) [inline .github/scripts/mk-generated.sh:35]: **Comment**: 🤣

**Review by ianbotsf — APPROVED** [review]
