### PR TITLE
fix: s3 default execution context attributes overriding previous section writers

### LINKED ISSUE #1165: S3 ExecutionContext defaults not being set
### Describe the bug

https://github.com/awslabs/aws-sdk-kotlin/pull/1151 broke the way we generate `mergeServiceDefaults`

This appears to only affect S3

### Expected behavior

Versions prior to 1.0.18:

```kotlin

    private fun mergeServiceDefaults(ctx: ExecutionContext) {
        ctx.putIfAbsentNotNull(AwsClientOption.Region, config.region)
        ctx.putIfAbsent(SdkClientOption.ClientName, config.clientName)
        ctx.putIfAbsent(SdkClientOption.LogMode, config.logMode)
        ctx.putIfAbsent(AwsSigningAttributes.SigningService, "s3")
        ctx.putIfAbsentNotNull(AwsSigningAttributes.SigningRegion, config.region)
        ctx.putIfAbsent(AwsSigningAttributes.CredentialsProvider, config.credentialsProvider)
        ctx.putIfAbsent(AwsSigningAttributes.NormalizeUriPath, false)
        ctx.putIfAbsent(AwsSigningAttributes.UseDoubleUriEncode, false)
        ctx.putIfAbsent(AwsSigningAttributes.SignedBodyHeader, AwsSignedBodyHeader.X_AMZ_CONTENT_SHA256)
    }

```

### Current behavior

Versions 1.0.18+

```kotlin
    private fun mergeServiceDefaults(ctx: ExecutionContext) {
        ctx.putIfAbsent(SdkClientOption.ClientName, config.clientName)
        ctx.putIfAbsent(SdkClientOption.LogMode, config.logMode)
        ctx.putIfAbsent(AwsSigningAttributes.NormalizeUriPath, false)
        ctx.putIfAbsent(AwsSigningAttributes.UseDoubleUriEncode, false)
        ctx.putIfAbsent(AwsSigningAttributes.SignedBodyHeader, AwsSignedBodyHeader.X_AMZ_CONTENT_SHA256)
    }
```

### Steps to Reproduce

This came about testing MRAP buckets and getting unexpected exception:

```
    Exception in thread "main" java.lang.IllegalStateException: No instance for AttributeKey(aws.smithy.kotlin.signing#AwsSigningRegion)
```

This should never happen since `SigningRegion` should always be set in the default execution context if a non-null `region` is configured.

### Possible Solution

_No response_

### Context

_No response_

### AWS Kotlin SDK version used

1.0.25

### Platform (JVM/JS/Native)

JVM

### Operating System and version

N/A

### PR DESCRIPTION
**Pull request by aajtodd**
## Issue \#

fixes #1165 

## Description of changes

Customization to render S3 specific execution context defaults was overriding other section writer integrations. 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: services/s3/common/test/aws/sdk/kotlin/services/s3/DefaultsTest.kt [hunk 1]
```diff
@@ -0,0 +1,55 @@
...
+import aws.smithy.kotlin.runtime.collections.get
+import aws.smithy.kotlin.runtime.http.interceptors.HttpInterceptor
+import aws.smithy.kotlin.runtime.httptest.buildTestConnection
+import aws.smithy.kotlin.runtime.io.use
+import kotlinx.coroutines.test.runTest
+import kotlin.test.Test
+import kotlin.test.assertEquals
+import kotlin.test.assertNotNull
+
+class DefaultsTest {
```
Comment (lauzadis) [inline services/s3/common/test/aws/sdk/kotlin/services/s3/DefaultsTest.kt:21]: naming: DefaultExecutionContextTest?

**Review by lauzadis — APPROVED** [review]

File: services/s3/common/test/aws/sdk/kotlin/services/s3/DefaultsTest.kt (hunk 1 above)
Comment (aajtodd) [reply services/s3/common/test/aws/sdk/kotlin/services/s3/DefaultsTest.kt:21]: I left it open ended on purpose if there are other "defaults" we want to test.
