### PR TITLE
fix: correctly convert key fields during paginated `Scan` and `Query` operations

### LINKED ISSUE #1596: DynamoDbMapper scan pagination ExclusiveStartKey issue
### Describe the bug

See discussion https://github.com/awslabs/aws-sdk-kotlin/discussions/1594.

Seems to be sending incorrect scan request json with ExclusiveStartKey containing all attributes instead of just primary key.

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Expected behavior

Scan request is sent correctly.

### Current behavior

Scan request incorrect.

### Steps to Reproduce

See discussion linked above.

### Possible Solution

_No response_

### Context

_No response_

### AWS SDK for Kotlin version

1.4.78-beta

### Platform (JVM/JS/Native)

JVM

### Operating system and version

MacOS

### PR DESCRIPTION
**Pull request by ianbotsf**
## Issue \#

Resolves #1596 

## Description of changes

This change corrects an oversight in key field conversion, namely relying on `ItemConverter` implementations to respect and properly handle the `onlyAttributes` argument. Given that implementations may vary widely and come from untrusted/unmodifiable sources, this change manually trims post-conversion key fields to retain only key attributes (dropping non-key attributes). Currently this affects four parameters:
* `DeleteItemRequest.key`
* `GetItemRequest.key`
* `QueryRequest.exclusiveStartKey`
* `ScanRequest.exclusiveStartKey`

This should eliminate service errors when sending too many fields in the above operations requests.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: hll/dynamodb-mapper/dynamodb-mapper/common/src/aws/sdk/kotlin/hll/dynamodbmapper/model/Item.kt [hunk 1]
```diff
@@ -8,7 +8,6 @@ import aws.sdk.kotlin.hll.dynamodbmapper.model.internal.ItemImpl
 import aws.sdk.kotlin.hll.dynamodbmapper.util.dynamicAttr
 import aws.sdk.kotlin.services.dynamodb.model.AttributeValue
 import aws.smithy.kotlin.runtime.ExperimentalApi
-import kotlin.jvm.JvmName
```
Comment (ianbotsf) [inline hll/dynamodb-mapper/dynamodb-mapper/common/src/aws/sdk/kotlin/hll/dynamodbmapper/model/Item.kt:11]: **Comment**: No clue why this is no longer necessary. 🤷‍♂️

**Review by lauzadis — APPROVED** [review]
