### PR TITLE
fix: apply optionalAuth backfill to missed cognitoidp methods

### LINKED ISSUE #874: Cognito associateSoftwareToken api return
### Describe the bug

Cognito `associateSoftwareToken` api returns following error when called after `respondToAuthChallenge` returns "MFA_SETUP" challengetype. 
```
UnknownException{message=Sign in failed., cause=aws.sdk.kotlin.runtime.auth.credentials.CredentialsProviderException: No credentials could be loaded from the chain: CredentialsProviderChain -> EnvironmentCredentialsProvider -> ProfileCredentialsProvider -> StsWebIdentityProvider -> EcsCredentialsProvider -> ImdsCredentialsProvider, recoverySuggestion=Sorry, we don't have a suggested fix for this error yet.}
```

### Expected behavior

`associateSoftwareToken`api as per the [documentation](https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_AssociateSoftwareToken.html) accepts the session string returned from the `respondToAuthChallenge` call for "MFA_SETUP" challengetype should return a secretCode to associate an authenticator app.

### Current behavior

`associateSoftwareToken` api returns following error when called with session string after `respondToAuthChallenge` returns "MFA_SETUP" challengetype and the user is not authenticated. 
```
UnknownException{message=Sign in failed., cause=aws.sdk.kotlin.runtime.auth.credentials.CredentialsProviderException: No credentials could be loaded from the chain: CredentialsProviderChain -> EnvironmentCredentialsProvider -> ProfileCredentialsProvider -> StsWebIdentityProvider -> EcsCredentialsProvider -> ImdsCredentialsProvider, recoverySuggestion=Sorry, we don't have a suggested fix for this error yet.}

### Steps to Reproduce

1) Enable MFA required for the userpool in Cognito.
2) Make `initiateAuth` api call with username & password and USER_SRP_AUTH authflowtype
3) `respondToAuthChallenge` api for PASSWORD_VERIFIER challengeType, this api call will return "MFA_SETUP" challenge
4) `associateSoftwareToken` api call with the session string from previous `respondToAuthChallenge` api call, this will cause a no CredentialProvider found error. Note: this call is made before the user is authenticated so not sure why it is expecting a CredentialProvider.

```
val initiateAuthResponse = cognitoIdentityProviderClient.initiateAuth {
                    authFlow = AuthFlowType.UserSrpAuth
                    clientId = configuration.userPool?.appClient
                    authParameters = authParams
                    clientMetadata = event.metadata
}

val response = cognitoIdentityProviderClient.respondToAuthChallenge {
                clientId = configuration.userPool?.appClient
                challengeName = "Password_verifier"
                this.challengeResponses = challengeResponses
                session = challenge.session
                clientMetadata = event.metadata
}

val associateSoftwareResponse = ognitoIdentityProviderClient.associateSoftwareToken {
      session = response.session
} ---> throws an error
```

### Possible Solution

N/A

### Context

_No response_

### AWS Kotlin SDK version used

0.21.3-beta

### Platform (JVM/JS/Native)

Native

### Operating System and version

Android 31

### PR DESCRIPTION
**Pull request by lucix-aws**
## Issue \#
Closes #874 

## Description of changes
Backfill missing `optionalAuth` trait in all cognitoidp methods.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: codegen/smithy-aws-kotlin-codegen/src/main/kotlin/aws/sdk/kotlin/codegen/customization/BackfillOptionalAuth.kt [hunk 1]
```diff
@@ -35,6 +35,7 @@ class BackfillOptionalAuth : KotlinIntegration {
         ),
         // https://docs.aws.amazon.com/cognito/latest/developerguide/security_iam_service-with-iam.html
         "com.amazonaws.cognitoidentityprovider#AWSCognitoIdentityProviderService" to setOf(
+            "com.amazonaws.cognitoidentityprovider#AssociateSoftwareToken",
```
Comment (harsh62) [inline codegen/smithy-aws-kotlin-codegen/src/main/kotlin/aws/sdk/kotlin/codegen/customization/BackfillOptionalAuth.kt:38]: Shouldn't [VerifySoftwareToken](https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_VerifySoftwareToken.html) also be part of this?

Comment (harsh62) [reply codegen/smithy-aws-kotlin-codegen/src/main/kotlin/aws/sdk/kotlin/codegen/customization/BackfillOptionalAuth.kt:38]: Like all the API's mentioned in this [doc](https://docs.aws.amazon.com/cognito/latest/developerguide/security_iam_service-with-iam.html)

Comment (lucix-aws) [reply codegen/smithy-aws-kotlin-codegen/src/main/kotlin/aws/sdk/kotlin/codegen/customization/BackfillOptionalAuth.kt:39]: The original intent of the integration wasn't to have the exhaustive list here - it was to only include ones in that list that were incorrectly missing `optionalAuth`.

Given that you found another missed one though, I've changed it to check all of the listed methods and apply the trait if missing. Checking the diff, it looks like there were 4 missed methods in total (including the one that triggered this PR and what you found).

**Review by aajtodd — APPROVED** [review]

**Review by lauzadis — APPROVED** [review]
