### PR TITLE
fix: apply clock skew interceptor to clients created via `invoke`

### LINKED ISSUE #1211: Clock skew interceptor is only applied when constructing clients via `fromEnvironment`
### Describe the bug

The `ClockSkewInterceptor` is only applied via `finalizeConfig` which is only invoked when constructing clients via `fromEnvironment`

### Expected behavior

`ClockSkew` should always be applied when constructing a client.

### Current behavior

Clock skew may or may not be applied

### Steps to Reproduce

N/A

### Possible Solution

_No response_

### Context

_No response_

### AWS Kotlin SDK version used

1.0.51

### Platform (JVM/JS/Native)

N/A

### Operating System and version

N/A

### PR DESCRIPTION
**Pull request by ianbotsf**
## Issue \#

Addresses #1211

## Description of changes

This change adds the clock skew interceptor to clients created via `invoke` (as opposed to `fromEnvironment`). It pulls in upstream changes from **smithy-kotlin** which add a `finalizeConfig` method to the abstract superclass from which `AbstractAwsSdkClientFactory` extends. This causes a naming conflict so the SDK's `suspend` `finalizeConfig` method has been renamed `finalizeEnvironmentalConfig`.

**Companion PR**: https://github.com/smithy-lang/smithy-kotlin/pull/1067

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by ianbotsf** [comment]
FYI I added the **ackhowledge-api-break** label to this PR because I think the breaks are safe but please chime in if you have differing opinions.

File: codegen/aws-sdk-codegen/src/test/kotlin/aws/sdk/kotlin/codegen/ServiceClientCompanionObjectWriterTest.kt [hunk 1]
```diff
@@ -23,18 +23,14 @@ class ServiceClientCompanionObjectWriterTest {
         ServiceClientCompanionObjectWriter().write(writer, null)
 
         val expected = """
-            public companion object : AbstractAwsSdkClientFactory<Config, Config.Builder, TestGeneratorClient, Builder>() {
```
Comment (lauzadis) [inline codegen/aws-sdk-codegen/src/test/kotlin/aws/sdk/kotlin/codegen/ServiceClientCompanionObjectWriterTest.kt:26]: This is a test for the companion object but there's no longer a companion object being generated, is that because there's no protocol? Can we add a protocol or maybe rename the test?

**Review by lauzadis — APPROVED** [review]
Approved, but let's talk about the API break

File: codegen/aws-sdk-codegen/src/test/kotlin/aws/sdk/kotlin/codegen/ServiceClientCompanionObjectWriterTest.kt (hunk 1 above)
Comment (ianbotsf) [reply codegen/aws-sdk-codegen/src/test/kotlin/aws/sdk/kotlin/codegen/ServiceClientCompanionObjectWriterTest.kt:26]: It's no longer `ServiceClientCompanionObjectWriter`'s job to _create_ the companion object, merely to _append_ things to sections of it, which the updated test reflects. In my view the class and test names are still correct.

**Comment by ianbotsf** [comment]
Discussed offline and this change is breaking enough that we don't want to push it directly to **main**. Updated base branch to **v1.2**. Will pursue a temporary fix strictly within **aws-sdk-kotlin** codegen until such time as we have another minor version bump.
