### PR TITLE
fix(codegen): render default endpoint resolver for machinelearning

### LINKED ISSUE #423: Machine learning customization is generating client without a default resolver
The machine learning customization introduced by #244 is causing the default client to be generated _without_ an endpoint resolver middleware for all but the `Predict` operation.

This is because the customization replaces the default resolver middleware for all operations but the customized protocol middleware only applies to the `Predict` operation.

### PR DESCRIPTION
**Pull request by aajtodd**
## Issue \#

fix #423 

## Description of changes

Ensure a default endpoint resolver is still registered for machine learning. The custom resolver for predict now runs after the default resolver to override the endpoint. We don't currently have a way to replace/override middleware per/operation in codegen. 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: codegen/smithy-aws-kotlin-codegen/src/main/kotlin/aws/sdk/kotlin/codegen/customization/machinelearning/MachineLearningEndpointCustomization.kt [hunk 1]
```diff
@@ -18,21 +17,22 @@ import software.amazon.smithy.model.shapes.OperationShape
...
+    // the default resolver middleware will still be present in the operation's execution stack, we just
+    // need to ensure that the custom resolver runs _after_ the default
     override fun customizeMiddleware(
         ctx: ProtocolGenerator.GenerationContext,
         resolved: List<ProtocolMiddleware>
-    ): List<ProtocolMiddleware> =
-        super
-            .customizeMiddleware(ctx, resolved)
-            .replace(endpointResolverMiddleware) { it is ResolveAwsEndpointMiddleware }
+    ): List<ProtocolMiddleware> = resolved + endpointResolverMiddleware
```
Comment (kggilmer) [inline codegen/smithy-aws-kotlin-codegen/src/main/kotlin/aws/sdk/kotlin/codegen/customization/machinelearning/MachineLearningEndpointCustomization.kt:25]: question

> the custom resolver runs _after_ the default

is enforced here by the fact that `endpointResolverMiddleware` is the last term here?

**Review by kggilmer — COMMENTED** [review]
Can you briefly mention testing steps here as I believe we don't have test coverage for this?

**Review by ianbotsf — APPROVED** [review]

File: codegen/smithy-aws-kotlin-codegen/src/main/kotlin/aws/sdk/kotlin/codegen/customization/machinelearning/MachineLearningEndpointCustomization.kt (hunk 1 above)
Comment (aajtodd) [reply codegen/smithy-aws-kotlin-codegen/src/main/kotlin/aws/sdk/kotlin/codegen/customization/machinelearning/MachineLearningEndpointCustomization.kt:25]: Yes, the endpoint resolver is there by default so this will always run after. The functionality is covered by a protocol test

**Comment by aajtodd** [comment]
> Can you briefly mention testing steps here as I believe we don't have test coverage for this?

I generated the machine learning client and noticed not endpoint resolver was registered in any of the operations except `Predict`. I regenerated after the change and verified that (1) every operation has an endpoint resolver and (2) `Predict` has the customized resolver registered after (again also covered by a protocol test)

**Review by kggilmer — APPROVED** [review]
