### PR TITLE
fix(rt): enforce only once shutdown logic for crt engine connections

### LINKED ISSUE #413: Segfault in CRT HTTP engine connection shutdown
## Describe the bug

One of our [async stress tests](https://github.com/awslabs/aws-sdk-kotlin/blob/v0.9.1-alpha/aws-runtime/http-client-engine-crt/jvm/test/aws/sdk/kotlin/runtime/http/engine/crt/AsyncStressTest.kt#L75) for the CRT HTTP engine is segfaulting on windows. 

```
2021-11-10T16:50:20.6269236Z [DEBUG] [2021-11-10T16:48:43Z] [000010d4] [channel-bootstrap] - id=000001AEABDCDA20: channel 000001AEABC0D800 shutdown with error 0.
2021-11-10T16:50:20.6270298Z [INFO] [2021-11-10T16:48:43Z] [000010d4] [http-connection] - 000001AEAD1C45B0: Client shutdown completed with error 0 (AWS_ERROR_SUCCESS).
2021-11-10T16:50:20.6271351Z [DEBUG] [2021-11-10T16:48:43Z] [000010d4] [connection-manager] - id=000001AEABDD7370: shutdown received for connection (id=000001AEAD1C45B0)
2021-11-10T16:50:20.6272476Z [DEBUG] [2021-11-10T16:48:43Z] [000010d4] [connection-manager] - id=000001AEABDD7370: snapshot - state=1, idle_connection_count=0, pending_acquire_count=695, pending_connect_count=1, vended_connection_count=15, open_connection_count=15, ref_count=1
2021-11-10T16:50:20.6273464Z [DEBUG] [2021-11-10T16:48:43Z] [000010d4] [channel] - id=000001AEABC0D800: destroying channel.
2021-11-10T16:50:20.6274148Z [DEBUG] [2021-11-10T16:48:43Z] [000010d4] [socket] - id=000001AEAC5CEB90, handle=FFFFFFFFFFFFFFFF: cleaning up socket.
2021-11-10T16:50:20.6274854Z [DEBUG] [2021-11-10T16:48:43Z] [000010d4] [socket] - id=000001AEAC5CEB90 handle=FFFFFFFFFFFFFFFF: closing
2021-11-10T16:50:20.6275597Z [DEBUG] [2021-11-10T16:48:43Z] [000010d4] [channel-bootstrap] - id=000001AEABDCDA20: releasing bootstrap reference
2021-11-10T16:50:20.6276397Z [DEBUG] [2021-11-10T16:48:43Z] [000010d4] [task-scheduler] - id=000001AEAD56DE70: Running on_channel_setup_complete task with <Running> status
2021-11-10T16:50:20.6277154Z [DEBUG] [2021-11-10T16:48:43Z] [000010d4] [channel] - id=000001AEABC0B400: setup complete, notifying caller.
2021-11-10T16:50:20.6278187Z [DEBUG] [2021-11-10T16:48:43Z] [000010d4] [channel] - id=000001AEABC0B400: message pool 000001AEADBDCDB0 found in event-loop local storage: using it.
2021-11-10T16:50:20.6279287Z [DEBUG] [2021-11-10T16:48:43Z] [000010d4] [channel-bootstrap] - id=000001AEABDCDA20: channel 000001AEABC0B400 setup succeeded: bootstrapping.
2021-11-10T16:50:20.6280343Z [TRACE] [2021-11-10T16:48:43Z] [000010d4] [channel] - id=000001AEABC0B400: creating new slot 000001AEAB4F3610.
2021-11-10T16:50:20.6281291Z [DEBUG] [2021-11-10T16:48:43Z] [000010d4] [socket-handler] - id=000001AEABE15510: Socket handler created with max_read_size of 262144
2021-11-10T16:50:20.6282185Z [TRACE] [2021-11-10T16:48:43Z] [000010d4] [socket] - id=000001AEAC5CC970 handle=00000000000008B0: subscribing to readable event
2021-11-10T16:50:20.6283430Z [TRACE] [2021-11-10T16:48:43Z] [000010d4] [channel-bootstrap] - id=000001AEABDCDA20: Setting up socket handler on channel 000001AEABC0B400 with handler 000001AEABE15510 on slot 000001AEAB4F3610.
2021-11-10T16:50:20.6284338Z [TRACE] [2021-11-10T16:48:43Z] [000010d4] [channel] - id=000001AEABC0B400: scheduling task with wrapper task id 000001AEABC0B668.
2021-11-10T16:50:20.6285093Z [TRACE] [2021-11-10T16:48:43Z] [000010d4] [event-loop] - id=000001AEABE064B0: scheduling task 000001AEABC0B668 in-thread for timestamp 0
2021-11-10T16:50:20.6285933Z [DEBUG] [2021-11-10T16:48:43Z] [000010d4] [task-scheduler] - id=000001AEABC0B668: Scheduling window update task task for immediate execution
2021-11-10T16:50:20.6286867Z [TRACE] [2021-11-10T16:48:43Z] [000010d4] [http-connection] - static: Socket connected, creating client connection object.
2021-11-10T16:50:20.6287651Z [TRACE] [2021-11-10T16:48:43Z] [000010d4] [channel] - id=000001AEABC0B400: creating new slot 000001AEAB4F3A90.
2021-11-10T16:50:20.6288593Z [INFO] [2021-11-10T16:48:43Z] [000010d4] [http-connection] - id=000001AEAD1C0FF0: HTTP/1.1 client connection established.
2021-11-10T16:50:20.6289497Z [DEBUG] [2021-11-10T16:48:43Z] [000010d4] [connection-manager] - id=000001AEABDD7370: Received new connection (id=000001AEAD1C0FF0) from http layer
2021-11-10T16:50:20.6290403Z [DEBUG] [2021-11-10T16:48:43Z] [000010d4] [connection-manager] - id=000001AEABDD7370: Grabbing pooled connection (000001AEAD1C0FF0)
2021-11-10T16:50:20.6291706Z [DEBUG] [2021-11-10T16:48:43Z] [000010d4] [connection-manager] - id=000001AEABDD7370: snapshot - state=1, idle_connection_count=0, pending_acquire_count=694, pending_connect_count=0, vended_connection_count=16, open_connection_count=16, ref_count=1
2021-11-10T16:50:20.6292957Z [DEBUG] [2021-11-10T16:48:43Z] [000010d4] [connection-manager] - id=000001AEABDD7370: Successfully completed connection acquisition with connection id=000001AEAD1C0FF0
2021-11-10T16:50:20.6293988Z [DEBUG] [2021-11-10T16:48:43Z] [000010d4] [http-connection] - ConnManager Acquired Conn: conn: 000001AEAD1C0FF0, manager: 000001AEABDD7370, err_code: 0,  err_str: Success.
2021-11-10T16:50:20.6294933Z [TRACE] [2021-11-10T16:48:43Z] [000010d4] [event-loop] - id=000001AEABE064B0: detected more scheduled tasks with the next occurring at 0, using timeout of 0.
2021-11-10T16:50:20.6295695Z [TRACE] [2021-11-10T16:48:43Z] [000010d4] [event-loop] - id=000001AEABE064B0: waiting for a maximum of 0 ms
2021-11-10T16:50:20.6296497Z [TRACE] [2021-11-10T16:48:43Z] [000010d4] [event-loop] - id=000001AEABE064B0: running scheduled tasks.
2021-11-10T16:50:20.6297358Z [DEBU# A fatal error has been detected by the Java Runtime Environment:
2021-11-10T16:50:20.6298104Z #
2021-11-10T16:50:20.6298599Z #  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ffccbc0da13, pid=436, tid=5812
2021-11-10T16:50:20.6299071Z #
2021-11-10T16:50:20.6299557Z # JRE version: OpenJDK Runtime Environment Temurin-11.0.13+8 (11.0.13+8) (build 11.0.13+8)
2021-11-10T16:50:20.6300736Z # Java VM: OpenJDK 64-Bit Server VM Temurin-11.0.13+8 (11.0.13+8, mixed mode, tiered, compressed oops, g1 gc, windows-amd64)
2021-11-10T16:50:20.6301502Z # Problematic frame:
2021-11-10T16:50:20.6301953Z # C  [AWSCRT_16365629109837760066350924725629aws-crt-jni.dll+0xda13]
2021-11-10T16:50:20.6302330Z #
2021-11-10T16:50:20.6303015Z # Core dump will be written. Default location: D:\a\aws-sdk-kotlin\aws-sdk-kotlin\aws-runtime\http-client-engine-crt\hs_err_pid436.mdmp
2021-11-10T16:50:20.6303887Z #
2021-11-10T16:50:20.6304270Z # An error report file with more information is saved as:
2021-11-10T16:50:20.6305026Z # D:\a\aws-sdk-kotlin\aws-sdk-kotlin\aws-runtime\http-client-engine-crt\hs_err_pid436.log
2021-11-10T16:50:20.6306498Z Compiled method (nm)   16764 6397     n 0       software.amazon.awssdk.crt.http.HttpClientConnection::httpClientConnectionShutdown (native)
2021-11-10T16:50:20.6308172Z  total in heap  [0x000001ae9fd04a90,0x000001ae9fd04e68] = 984
2021-11-10T16:50:20.6308811Z  relocation     [0x000001ae9fd04c08,0x000001ae9fd04c38] = 48
2021-11-10T16:50:20.6309567Z  main code      [0x000001ae9fd04c40,0x000001ae9fd04e60] = 544
2021-11-10T16:50:20.6310179Z  oops           [0x000001ae9fd04e60,0x000001ae9fd04e68] = 8
2021-11-10T16:50:20.6310582Z #
2021-11-10T16:50:20.6310958Z # If you would like to submit a bug report, please visit:
2021-11-10T16:50:20.6311587Z #   https://github.com/adoptium/adoptium-support/issues
2021-11-10T16:50:20.6312481Z # The crash happened outside the Java Virtual Machine in native code.
2021-11-10T16:50:20.6313096Z # See problematic frame for where to report the bug.
2021-11-10T16:50:20.6313482Z #
2021-11-10T16:50:20.6314045Z G] [2021-11-10T16:48:43Z] [000010d4] [task-scheduler] - id=000001AEABC0B668: Running window update task task with <Running> status
2021-11-10T16:50:20.6315302Z [TRACE] [2021-11-10T16:48:43Z] [000010d4] [socket-handler] - id=000001AEABE15510: increment read window message received, scheduling task for another read operation.
2021-11-10T16:50:20.6316234Z [TRACE] [2021-11-10T16:48:43Z] [000010d4] [channel] - id=000001AEABC0B400: scheduling task with wrapper task id 000001AEABE15548.
2021-11-10T16:50:20.6317045Z [TRACE] [2021-11-10T16:48:43Z] [000010d4] [event-loop] - id=000001AEABE064B0: scheduling task 000001AEABE15548 in-thread for timestamp 0
2021-11-10T16:50:20.6318064Z [DEBUG] [2021-11-10T16:48:43Z] [000010d4] [task-scheduler] - id=000001AEABE15548: Scheduling socket_handler_read_on_window_increment task for immediate execution
2021-11-10T16:50:20.6319063Z [TRACE] [2021-11-10T16:48:43Z] [000010d4] [event-loop] - id=000001AEABE064B0: detected more scheduled tasks with the next occurring at 0, using timeout of 0.
2021-11-10T16:50:20.6319863Z [TRACE] [2021-11-10T16:48:43Z] [000010d4] [event-loop] - id=000001AEABE064B0: waiting for a maximum of 0 ms
2021-11-10T16:50:20.6320513Z [TRACE] [2021-11-10T16:48:43Z] [000010d4] [event-loop] - id=000001AEABE064B0: running scheduled tasks.
2021-11-10T16:50:20.6321859Z [DEBUG] [2021-11-10T16:48:43Z] [000010d4] [task-scheduler] - id=000001AEABE15548: Running socket_handler_read_on_window_increment task with <Running> status
2021-11-10T16:50:20.6322785Z [TRACE] [2021-11-10T16:48:43Z] [000010d4] [socket-handler] - id=000001AEABE15510: invoking read. Downstream window 262144, max_to_read 262144
2021-11-10T16:50:20.6332389Z [TRACE] [2021-11-10T16:48:43Z] [000010d4] [channel] - id=000001AEABC0B400: acquired message 000001AEB3D52740 of capacity 262144 from pool 000001AEADBDCDB0. Requested size was 262144
2021-11-10T16:50:20.6333367Z [TRACE] [2021-11-10T16:48:43Z] [000010d4] [socket] - id=000001AEAC5CC970 handle=00000000000008B0: reading from socket
2021-11-10T16:50:20.6334396Z [TRACE] [2021-11-10T16:48:43Z] [000010d4] [socket] - id=000001AEAC5CC970 handle=00000000000008B0: read would block, scheduling 0 byte read and returning
2021-11-10T16:50:20.6335476Z [TRACE] [2021-11-10T16:48:43Z] [000010d4] [socket-handler] - id=000001AEAB4F3630: total read on this tick 0
2021-11-10T16:50:20.6336438Z [TRACE] [2021-11-10T16:48:43Z] [000010d4] [socket-handler] - id=000001AEABE15510: out of data to read on socket. Waiting on event-loop notification.
2021-11-10T16:50:20.6337436Z [TRACE] [2021-11-10T16:48:43Z] [000010d4] [event-loop] - id=000001AEABE064B0: detected more scheduled tasks with the next occurring at 859251931100, using timeout of 493.
2021-11-10T16:50:20.6338377Z [TRACE] [2021-11-10T16:48:43Z] [000010d4] [event-loop] - id=000001AEABE064B0: waiting for a maximum of 493 ms
2021-11-10T16:50:20.6338769Z 
```

## Steps to Reproduce

I've only been able to reproduce this in CI so far. Here is a failing CI run with full logs and JVM dump as an artifact:
https://github.com/awslabs/aws-sdk-kotlin/actions/runs/1446034029

## Possible Solution

CRT team is currently investigating

### PR DESCRIPTION
**Pull request by aajtodd**
## Issue \#

fixes #413

## Description of changes

Fixes the segfault that can happen when an exception is handled twice leading to a connection being closed after it has been free'd. This change refactors the handling of the connection close logic to be handled in a single place regardless of why the connection is being closed.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by ianbotsf — APPROVED** [review]

File: aws-runtime/http-client-engine-crt/common/src/aws/sdk/kotlin/runtime/http/engine/crt/SdkStreamResponseHandler.kt [hunk 1]
```diff
@@ -162,13 +169,19 @@ internal class SdkStreamResponseHandler(
...
         // on the window to be incremented to proceed (i.e. the user didn't consume the stream for whatever reason
-        // and more data is pending arrival).
-        val forceClose = lock.withLock { !streamCompleted }
+        // and more data is pending arrival). It can also happen if the coroutine for this request is cancelled
+        // before onResponseComplete fires.
+        lock.withLock {
+            val forceClose = !streamCompleted
+
+            if (forceClose) {
+                logger.trace { "stream did not complete before job, forcing connection shutdown! handler=$this; conn=$conn; stream=$crtStream" }
```
Comment (kggilmer) [inline aws-runtime/http-client-engine-crt/common/src/aws/sdk/kotlin/runtime/http/engine/crt/SdkStreamResponseHandler.kt:180]: comment

Perhaps this should be a higher level message, like `warn`.  From past experience it is often useful to know when partial results where received.

**Review by kggilmer — APPROVED** [review]

File: aws-runtime/http-client-engine-crt/common/src/aws/sdk/kotlin/runtime/http/engine/crt/SdkStreamResponseHandler.kt (hunk 1 above)
Comment (aajtodd) [reply aws-runtime/http-client-engine-crt/common/src/aws/sdk/kotlin/runtime/http/engine/crt/SdkStreamResponseHandler.kt:180]: This doesn't necessarily mean partial results though. Technically it just means the coroutine job completed before consuming the entire response which could happen because of an exception _or_ simply because the consumer doesn't read the entire body. 

If we actually had a stream cancellation API then we wouldn't need to force close the connection which would make this less heavy handed.

I don't think I'd make it `warn` because in the case of an exception they'll be forced to handle it anyway and the exception is your signal. In the case of explicitly not consuming the entire body it's not a warning since the consumer is choosing it. Perhaps `debug` would be better than `trace` though?
